# Generated by Django 5.1.2 on 2025-01-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trombi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-annee_debut_exp'], 'verbose_name': 'Expérience', 'verbose_name_plural': 'Expériences'},
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='annee_debut',
            new_name='annee_debut_exp',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='annee_fin',
            new_name='annee_fin_exp',
        ),
    ]
