# Generated by Django 5.1.2 on 2025-01-23 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombi', '0002_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='cv_competences', to='trombi.competence'),
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_experiences',
            field=models.ManyToManyField(blank=True, related_name='cv_experiences', to='trombi.experience'),
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_formations',
            field=models.ManyToManyField(blank=True, related_name='cv_formations', to='trombi.formation'),
        ),
        migrations.AddField(
            model_name='cv',
            name='langues',
            field=models.ManyToManyField(blank=True, related_name='cv_langues', to='trombi.langue'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='cv',
            field=models.ManyToManyField(blank=True, related_name='competences_cv', to='trombi.cv'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trombi.template'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='cv',
            field=models.ManyToManyField(blank=True, related_name='experiences_cv', to='trombi.cv'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='cv',
            field=models.ManyToManyField(blank=True, related_name='formations_cv', to='trombi.cv'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='cv',
            field=models.ManyToManyField(blank=True, related_name='langues_cv', to='trombi.cv'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='cv',
            field=models.ManyToManyField(blank=True, related_name='projets_cv', to='trombi.cv'),
        ),
    ]
